import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from "react";
import { MapPin } from "lucide-react";
import PlaceToVisit from "./PlaceToVisitCard";
import HotelRecomandationCard from "./HotelRecomandationCard";
import SearchWithFilter from "./SearchWithFilter";
export default function TripPlanner() {
    const [selectedPlaces, setSelectedPlaces] = useState([]);
    return (_jsxs("div", { className: "bg-gradient-to-b from-blue-50 to-white", children: [_jsx("div", { className: "py-10 px-6 sm:px-10", children: _jsx("div", { className: "max-w-7xl mx-auto", children: _jsxs("div", { className: "flex flex-col md:flex-row gap-8", children: [_jsx(SearchWithFilter, {}), _jsx("div", { className: "md:w-1/3", children: _jsxs("div", { className: "bg-white rounded-xl p-6 shadow-md border border-gray-200", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-800 mb-4", children: "Selected Places" }), selectedPlaces.length > 0 ? (_jsxs(_Fragment, { children: [_jsx("ul", { className: "space-y-3", children: selectedPlaces.map((place) => (_jsxs("li", { className: "flex items-center text-gray-700 text-sm gap-2", children: [_jsx(MapPin, { className: "w-4 h-4 text-green-500" }), place.name] }, place.id))) }), _jsx("button", { className: "mt-6 w-full py-2.5 bg-green-600 hover:bg-green-700 text-white rounded-xl text-sm transition", children: "Generate Route" })] })) : (_jsx("div", { className: "text-center text-gray-500 py-6", children: "No places selected yet" }))] }) })] }) }) }), _jsx("div", { className: "  px-6 sm:px-10", children: _jsx("div", { className: "max-w-7xl mx-auto space-y-14", children: _jsxs("section", { children: [_jsx("h2", { className: "text-2xl font-semibold text-gray-800 mb-6", children: "Places to Visit" }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6", children: [_jsx(PlaceToVisit, {}), _jsx(PlaceToVisit, {}), _jsx(PlaceToVisit, {}), _jsx(PlaceToVisit, {}), _jsx(PlaceToVisit, {}), _jsx(PlaceToVisit, {})] })] }) }) }), _jsxs("div", { className: "flex justify-center items-center gap-4 mt-3 pb-3", children: [_jsxs("button", { className: "flex items-center gap-2 px-2 py-2 rounded-lg border border-gray-300 bg-white text-gray-700 hover:bg-gray-100 hover:shadow-md transition-all duration-200 text-sm font-medium", children: [_jsx("span", { className: "text-lg", children: "\u2190" }), "Previous"] }), _jsxs("button", { className: "flex items-center gap-2 px-2 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700 hover:shadow-md transition-all duration-200 text-sm font-medium", children: ["Next ", _jsx("span", { className: "text-lg", children: "\u2192" })] })] })] }));
}
{
    /* Hotels */
}
_jsxs("section", { children: [_jsx("h2", { className: "text-2xl font-semibold text-gray-800 mb-6", children: "Hotel Recommendations" }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6", children: [_jsx(HotelRecomandationCard, {}), _jsx(HotelRecomandationCard, {}), _jsx(HotelRecomandationCard, {}), _jsx(HotelRecomandationCard, {})] })] });
