version: '3.8'

services:
  # Shell Container (Host)
  shell:
    build:
      context: ..
      dockerfile: docker/shell.Dockerfile
    ports:
      - "5000:80"
    environment:
      - NODE_ENV=production
    networks:
      - travel-ecosystem
    depends_on:
      - blog
      - visa-explorer
      - trip-planner

  # Blog Micro-frontend
  blog:
    build:
      context: ..
      dockerfile: docker/blog.Dockerfile
    ports:
      - "5001:80"
    environment:
      - NODE_ENV=production
    networks:
      - travel-ecosystem

  # Visa Explorer Micro-frontend
  visa-explorer:
    build:
      context: ..
      dockerfile: docker/visa-explorer.Dockerfile
    ports:
      - "5002:80"
    environment:
      - NODE_ENV=production
    networks:
      - travel-ecosystem

  # Travel Hub Micro-frontend (Placeholder)
  # travel-hub:
  #   build:
  #     context: ..
  #     dockerfile: docker/travel-hub.Dockerfile
  #   ports:
  #     - "5003:80"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - travel-ecosystem

  # Trip Planner Micro-frontend
  trip-planner:
    build:
      context: ..
      dockerfile: docker/trip-planner.Dockerfile
    ports:
      - "5004:80"
    environment:
      - NODE_ENV=production
    networks:
      - travel-ecosystem

  # Volunteering Micro-frontend (Placeholder)
  # volunteering:
  #   build:
  #     context: ..
  #     dockerfile: docker/volunteering.Dockerfile
  #   ports:
  #     - "5005:80"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - travel-ecosystem

networks:
  travel-ecosystem:
    driver: bridge
