version: '3.8'

services:
  # Shell Container (Host) - Development
  shell:
    build:
      context: ..
      dockerfile: docker/shell.dev.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../shell:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - travel-ecosystem
    command: npm run dev

  # Blog Micro-frontend - Development
  blog:
    build:
      context: ..
      dockerfile: docker/blog.dev.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ../apps/blog:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - travel-ecosystem
    command: npm run dev

  # Visa Explorer Micro-frontend - Development
  visa-explorer:
    build:
      context: ..
      dockerfile: docker/visa-explorer.dev.Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ../apps/visa-explorer:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - travel-ecosystem
    command: npm run dev

  # Trip Planner Micro-frontend - Development
  trip-planner:
    build:
      context: ..
      dockerfile: docker/trip-planner.dev.Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - ../apps/trip-planner:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - travel-ecosystem
    command: npm run dev

networks:
  travel-ecosystem:
    driver: bridge
