version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: travel-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: travel_discovery
    networks:
      - travel-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: travel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - travel-network
    restart: unless-stopped

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: travel-weaviate
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - travel-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  weaviate_data:
    driver: local

networks:
  travel-network:
    driver: bridge
