version: '3.8'

services:
  # Neo4j graph database for discovery-engine
  neo4j:
    image: neo4j:5.12
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

  # MongoDB for blog service
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # discovery-engine service
  discovery-engine:
    build:
      context: ./services/discovery-engine
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    depends_on:
      - neo4j
    volumes:
      - ./services/discovery-engine:/app
      - /app/node_modules

  # visa-explore service
  visa-explore:
    build:
      context: ./services/visa-explore
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      PORT: 4001
    volumes:
      - ./services/visa-explore:/app
      - /app/node_modules

  # blog service
  blog:
    build:
      context: ./services/blog
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      PORT: 4002
      MONGO_URI: mongodb://mongo:27017/blog
    depends_on:
      - mongo
    volumes:
      - ./services/blog:/app
      - /app/node_modules

  # volenteering service
  volenteering:
    build:
      context: ./services/volenteering
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    environment:
      PORT: 4003
    volumes:
      - ./services/volenteering:/app
      - /app/node_modules

volumes:
  neo4j-data:
  mongo-data:
