import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Clock } from '@phosphor-icons/react';
import { IoCloseSharp, } from 'react-icons/io5';
import { TbDeviceMobileMessage } from 'react-icons/tb';
import { CiMenuKebab } from 'react-icons/ci';
const UserInfo = ({ handleTogleInfo, selectedUser }) => {
    return (_jsxs("div", { className: "border-l border-gray-200 h-[87vh] w-full max-w-xs bg-white flex flex-col shadow-md", children: [_jsxs("div", { className: "flex items-center justify-between px-6 py-5 border-b border-gray-300 bg-white", children: [_jsx("h2", { className: "text-lg font-semibold text-gray-800", children: "Profile" }), _jsx("button", { onClick: handleTogleInfo, className: "text-gray-500 hover:text-red-500 transition duration-200", children: _jsx(IoCloseSharp, { size: 22 }) })] }), _jsxs("div", { className: "flex flex-col items-center mt-6", children: [_jsx("img", { src: selectedUser?.profileImage, className: "w-36 h-36 rounded-xl object-cover border-4 border-blue-100 shadow-md", alt: "Profile" }), _jsx("div", { className: "mt-4 text-xl font-semibold text-gray-900", children: selectedUser?.firstName }), _jsx("span", { className: "text-sm text-gray-500", children: "Traveller" })] }), _jsx("div", { className: "px-6 mt-8", children: _jsxs("div", { className: "flex items-center space-x-2 text-sm text-gray-700", children: [_jsx(Clock, { size: 20 }), _jsx("span", { children: "7:15 PM Local Time" })] }) }), _jsxs("div", { className: "mt-8 px-6 space-y-3", children: [_jsxs("button", { className: "w-full flex items-center justify-center gap-2 bg-blue-500 text-white font-medium py-2 rounded-lg shadow hover:bg-blue-600 transition", children: [_jsx(TbDeviceMobileMessage, { size: 20 }), "Message"] }), _jsx("button", { className: "w-full flex items-center justify-center gap-2 bg-purple-500 text-white font-medium py-2 rounded-lg shadow hover:bg-purple-600 transition", children: "Huddle" }), _jsxs("button", { className: "w-full flex items-center justify-center gap-2 bg-gray-100 text-gray-700 py-2 rounded-lg shadow hover:bg-gray-200 transition", children: [_jsx(CiMenuKebab, { size: 20 }), "More"] })] })] }));
};
export default UserInfo;
